title: In My Dream World
author: Ashutosh
email: ashumsa3@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Writing the things that should have been happened.

# social links
twitter_username: ashu_msa_3 # DO NOT include the @ character, or else the build will fail!
github_username:  ashumsa3 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
